GET http://localhost:4000/post HTTP/1.1
content-type: application/json
Authorization:Bearer Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGluYSIsImlhdCI6MTYzMzM1OTcyMywiZXhwIjoxNjMzMzU5NzM4fQ.mDcmXO_LTyihAtFoh7deA1QNI6Jo5Q464IwICnHkQQ8

{
    "username":"tina"
}


###
POST http://localhost:5000/login HTTP/1.1
content-type: application/json


{
    "username":"tina"
}
###
POST http://localhost:5000/token HTTP/1.1
content-type: application/json


{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGluYSIsImlhdCI6MTYzMzM1OTY3OX0.X9HuSgmyFOO1ZFQxoS0MaNPhDbv1us_0UR5Y7VNLXG8"
}
###
delete http://localhost:5000/logout HTTP/1.1
content-type: application/json


{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGluYSIsImlhdCI6MTYzMzM1OTY3OX0.X9HuSgmyFOO1ZFQxoS0MaNPhDbv1us_0UR5Y7VNLXG8"
}